on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/youload/ # navigate into the folder
            git clone https://github.com/leighton-tidwell/youload app # clone the repo into the 'app' folder
            cd youload # navigate into the repo
            npm install # install dependencies 
            pm2 start app.js # start as a background service.
        env:
          CI: true
          PORT: ${{ secrets.APPPORT }}
          DB_LINK: ${{ secrets.DB_LINK }}
