on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        env:
          PORT: ${{ secrets.APPPORT }}
          DB_LINK: ${{ secrets.DB_LINK }}
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/youload/ # navigate into the folder
            git pull
            pm2 restart index.js # start as a background service.
